version: "3.8"

name: docker-viriyah-com

services:
  php-apache-environment:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: viriyah-com-apache2-ssl-php7.2-sqlsrv5.7
    image: viriyah-com-webapp
    volumes:
      - ./src:/var/www/html/
    ports:
      - 80:80
      - 443:443

  sql-server:
    container_name: viriyah-com-sqlserver2019
    image: mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=!QAZxsw2
    volumes:
      - /var/opt/mssql
